id = "modern-icons"
name = "Modern Icons Theme"
version = "0.4.0"
schema_version = 1
authors = ["Ravindra Singh <rbmorena42@gmail.com>"]
description = "VSCode icons theme for Zed"
repository = "https://github.com/badrat-in/zed-modern-icons"
